### ISSUE TITLE
Consider implementhing own scroll bar.

### ISSUE THREAD

**Issue by turakvlad** [turakvlad/noonwander#14]
Watch at the scroll bar at this [site](http://noonwander.tumblr.com/). Does it make sense to implement to our site? How does it work? What will we need? Only CSS? What about mobile phones? Does it work on old mobile phones?

**Comment by zizizi17** [comment]
В залежності від того, як хоче Наталя. Якщо робити динамічну підгрузку нових постів, то так, варто робити такий скрол.
А отут, воно ж буду асинхронно робити запити до бази, через там кожних 700 пікселів наприклад і тоді додавати в ДОМ чи ні? 
Нам треба буде ж jquery чи ні?
